const projects = [
  {id:'agentguard',name:'AgentGuard OS',desc:'A prototype governance workspace for reviewing, approving and auditing AI-agent actions.',roles:['AI Engineer','Software Engineer','AI Consultant','AI Product / Automation'],problem:'Teams need clear oversight when automated agents take consequential actions.',features:['Policy-based action review','Human approval checkpoints','Audit trail and risk views'],tech:['Python','FastAPI','SQLite','JavaScript','LLM APIs'],value:'Shows responsible AI thinking, API design and human-in-the-loop workflow design.',status:'Prototype',overview:'AgentGuard OS explores how teams could supervise AI agents without losing the speed benefits of automation.',solution:'A review layer that classifies proposed agent actions, routes higher-risk decisions to a person, and records the outcome for later inspection.',workflow:['Agent proposes action','Policy layer evaluates risk','Reviewer approves or rejects','Decision enters audit trail'],proves:'I can think beyond model output to controls, users, traceability and safe system behaviour.',next:'Add richer policy configuration, automated evaluation tests and role-based access controls.'},
  {id:'iris',name:'Iris Job Assistant',desc:'An AI-assisted workspace that organises job discovery, application research and tailored preparation.',roles:['AI Engineer','Software Engineer','AI Product / Automation'],problem:'Job seekers repeat fragmented research and preparation work across every application.',features:['Role tracking workflow','Relevance analysis','Assisted preparation with user review'],tech:['Python','FastAPI','JavaScript','SQLite','LLM APIs'],value:'Demonstrates workflow automation, product judgement and careful use of LLM assistance.',status:'Demo ready',overview:'Iris brings the repetitive parts of a job search into one understandable workflow while keeping final decisions with the user.',solution:'A modular assistant for collecting roles, comparing requirements, organising application evidence and generating editable preparation material.',workflow:['Capture opportunity','Extract requirements','Match user evidence','Prepare and review'],proves:'I can translate a messy user journey into a coherent full-stack product concept.',next:'Improve evaluation of generated content, add calendar integrations and expand accessibility testing.'},
  {id:'impact',name:'AI Impact OS',desc:'A decision workspace for finding, prioritising and planning responsible AI automation opportunities.',roles:['AI Engineer','Software Engineer','AI Consultant','AI Product / Automation'],problem:'Businesses often jump to AI tools before defining the workflow, value or risk.',features:['Opportunity discovery','Impact–effort prioritisation','Responsible adoption roadmap'],tech:['Python','Streamlit','pandas','LLM APIs'],value:'Connects technical feasibility with business needs, adoption and governance.',status:'Case study',overview:'AI Impact OS is a consulting-style prototype for moving from vague AI ambition to a prioritised, responsible action plan.',solution:'A guided assessment maps workflows, scores candidate opportunities and surfaces risks, dependencies and practical next steps.',workflow:['Map business workflow','Identify friction','Score opportunities','Build adoption roadmap'],proves:'I can frame AI as an organisational and product decision—not just a model choice.',next:'Validate scoring with domain experts and add configurable industry templates.'},
  {id:'nestdore',name:'Property-Match / Nestdore',desc:'A property discovery concept that ranks homes against a buyer’s real preferences.',roles:['Software Engineer','AI Product / Automation'],problem:'Property search filters are rigid and struggle to express nuanced buyer priorities.',features:['Preference-based matching','Explainable ranking','Saved shortlist workflow'],tech:['Python','FastAPI','PostgreSQL','JavaScript','REST APIs'],value:'Shows search, ranking, API and user-centred recommendation thinking.',status:'Prototype',overview:'Nestdore explores a more helpful property journey built around trade-offs rather than a brittle checklist.',solution:'A recommendation layer converts weighted preferences into ranked results and explains why each property fits.',workflow:['Capture priorities','Normalise listings','Calculate match score','Explain and shortlist'],proves:'I understand recommendation logic, data modelling and explainable product experiences.',next:'Use real permitted listing data, improve geospatial features and test ranking quality with users.'},
  {id:'audit',name:'ML Audit Engine',desc:'A model inspection toolkit for surfacing performance, fairness and reliability concerns.',roles:['AI Engineer','Data Analyst','AI Consultant'],problem:'A single accuracy score can hide weak segments, imbalance and risky model behaviour.',features:['Segment performance checks','Bias indicator views','Reproducible audit reports'],tech:['Python','pandas','scikit-learn','Streamlit','NumPy'],value:'Demonstrates responsible ML evaluation, analytical rigour and explainable reporting.',status:'Code available',overview:'ML Audit Engine makes common model-quality questions easier to inspect and communicate.',solution:'A repeatable audit workflow loads predictions and protected attributes, calculates diagnostics, and presents caveated findings.',workflow:['Load model outputs','Validate data','Run diagnostics','Review report'],proves:'I can evaluate models critically and communicate limitations rather than treating metrics as proof of safety.',next:'Add drift monitoring, confidence intervals and broader fairness definitions with clear usage guidance.'},
  {id:'casino',name:'Casino Customer Insights Dashboard',desc:'An analytical dashboard for understanding customer behaviour, segments and retention signals.',roles:['Data Analyst'],problem:'Raw transaction and visit data is difficult for decision-makers to interpret quickly.',features:['Customer segmentation','Behaviour trends','Decision-focused KPI views'],tech:['Python','pandas','SQL','Streamlit'],value:'Shows data cleaning, analytical storytelling and stakeholder-focused dashboard design.',status:'Case study',overview:'This academic portfolio case study turns customer activity data into a clear exploration tool.',solution:'A dashboard combines validated metrics, segment comparisons and filters to support informed discussion without implying causation.',workflow:['Clean activity data','Define metrics','Explore segments','Communicate findings'],proves:'I can move from raw data to transparent, decision-ready analysis.',next:'Add cohort analysis, metric definitions in-context and formal usability feedback.'},
  {id:'jobmarket',name:'Job Market Intelligence Dashboard',desc:'A dashboard that turns job-listing data into signals about roles, skills and demand.',roles:['Data Analyst','AI Consultant'],problem:'Candidates and teams struggle to see patterns across large volumes of job listings.',features:['Skill-demand analysis','Role and location filters','Trend-ready data pipeline'],tech:['Python','pandas','SQL','Streamlit'],value:'Demonstrates data transformation, market analysis and accessible insight design.',status:'Prototype',overview:'The dashboard explores how public job-listing data can reveal useful patterns while respecting data-source constraints.',solution:'A repeatable cleaning and analysis flow standardises role and skill terms before presenting filterable summaries.',workflow:['Collect permitted data','Clean and classify','Aggregate patterns','Explore dashboard'],proves:'I can structure noisy text-derived data and turn it into understandable business intelligence.',next:'Add a documented live-data source, stronger taxonomy evaluation and time-series comparisons.'},
  {id:'resume',name:'Resume Relevance Analyzer',desc:'An explainable comparison tool that maps CV evidence to job requirements.',roles:['Data Analyst','AI Engineer'],problem:'Keyword scores give candidates little useful guidance and can encourage misleading optimisation.',features:['Requirement extraction','Evidence mapping','Transparent gap prompts'],tech:['Python','NLP','Embeddings','Streamlit'],value:'Shows NLP application, explainability and responsible recruitment-product thinking.',status:'Code available',overview:'This tool helps a user inspect alignment between their existing evidence and a role—without pretending to predict hiring outcomes.',solution:'Semantic comparison highlights likely matches and gaps, then points users back to the underlying text for human judgement.',workflow:['Parse documents','Extract requirements','Compare evidence','Review and revise'],proves:'I can use embeddings as one component in a transparent, human-led decision aid.',next:'Build a labelled evaluation set, test accessibility and add stronger uncertainty communication.'},
  {id:'mixologist',name:'Smart Mixologist',desc:'A playful recommendation app that suggests cocktails from available ingredients and preferences.',roles:['Software Engineer','AI Product / Automation'],problem:'People need useful suggestions from incomplete ingredient sets and varied tastes.',features:['Ingredient matching','Preference-aware suggestions','Clear recipe presentation'],tech:['JavaScript','HTML','CSS','REST APIs'],value:'Demonstrates front-end product craft, recommendation logic and API integration.',status:'Demo ready',overview:'Smart Mixologist turns a simple recommendation problem into a polished, accessible user flow.',solution:'Client-side logic combines ingredient availability and preferences, then presents suitable options with clear explanations.',workflow:['Choose ingredients','Set preferences','Rank recipes','Review instructions'],proves:'I can build approachable interfaces and make ranking logic useful to everyday users.',next:'Add allergy warnings, stronger data validation and offline favourites.'}
];

const roleData={
  'AI Engineer':{pitch:'I combine an AI degree with projects that focus on evaluation, governance, retrieval and practical LLM workflows—not just model demos.',skills:['Python','scikit-learn','LLM APIs','Embeddings','FastAPI'],talk:['How AgentGuard handles risky actions','How I would evaluate LLM-assisted features','Trade-offs between automation and human review'],projects:['agentguard','iris','impact','audit']},
  'Software Engineer':{pitch:'I build end-to-end prototypes with clear data flows, APIs and interfaces, and I care about maintainability, user needs and honest scope.',skills:['Python','JavaScript','FastAPI','SQL','REST APIs'],talk:['API and data-model decisions in Iris','Recommendation flow in Nestdore','How I would move a prototype toward production'],projects:['iris','agentguard','nestdore','impact']},
  'Data Analyst':{pitch:'I use Python and SQL to turn messy data into transparent analysis, with attention to definitions, limitations and decision-ready presentation.',skills:['SQL','pandas','Python','Streamlit','Data visualisation'],talk:['Metric design in the customer dashboard','Cleaning noisy job-listing data','Communicating fairness metrics responsibly'],projects:['casino','jobmarket','audit','resume']},
  'AI Consultant':{pitch:'I connect AI capability to workflow value, adoption constraints and responsible governance—while staying grounded about what a prototype proves.',skills:['AI opportunity mapping','Governance','Data analysis','LLM workflows','Stakeholder communication'],talk:['Prioritising AI use cases by value and risk','Designing useful human checkpoints','Explaining technical trade-offs clearly'],projects:['impact','agentguard','jobmarket','audit']},
  'AI Product / Automation':{pitch:'I’m strongest where user workflow, AI capability and product decisions meet: finding friction, designing assistance and keeping people in control.',skills:['Workflow design','LLM APIs','FastAPI','JavaScript','Product prototyping'],talk:['User journey choices in Iris','Impact–effort prioritisation','Designing explainable recommendations'],projects:['iris','impact','agentguard','nestdore']}
};
const skillGroups={'AI / ML':['Python','scikit-learn','TensorFlow','PyTorch','Embeddings','Vector search','LLM APIs'],'Backend / APIs':['FastAPI','REST APIs','SQLite','PostgreSQL','MongoDB'],'Frontend':['HTML','CSS','JavaScript'],'Data / SQL':['SQL','pandas','NumPy','Streamlit'],'Automation / Tools':['Git','GitHub','GitHub Actions','Docker'],'Cloud / Deployment':['AWS basics','GitHub Pages','Supabase','pgvector']};
const impacts=[['AI safety and governance','AgentGuard OS'],['Recruitment automation','Iris · Resume Analyzer'],['Business workflow automation','AI Impact OS · Iris'],['Data insight dashboards','Casino · Job Market'],['ML model auditability','ML Audit Engine'],['Search and recommendation','Nestdore · Smart Mixologist'],['Customer analytics','Casino Dashboard'],['Job market intelligence','Job Market Dashboard']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const grid=$('#project-grid'),modal=$('#case-modal'),toast=$('#toast'); let activeRole='all';

function renderProjects(){const q=$('#project-search').value.toLowerCase().trim(),tech=$('#tech-filter').value;const list=projects.filter(p=>(activeRole==='all'||p.roles.includes(activeRole))&&(tech==='all'||p.tech.includes(tech))&&(!q||JSON.stringify(p).toLowerCase().includes(q)));grid.innerHTML=list.map(p=>`<article class="project-card reveal visible ${activeRole!=='all'?'recommended':''}" data-id="${p.id}">${activeRole!=='all'?'<span class="recommended-flag">ROLE MATCH</span>':''}<span class="project-index">PROJECT / ${String(projects.indexOf(p)+1).padStart(2,'0')}</span><h3>${p.name}</h3><p class="project-desc">${p.desc}</p><p class="role-match">Best for ${p.roles.slice(0,2).join(' · ')}</p><div class="project-detail"><span>Problem</span>${p.problem}</div><div class="project-detail employer-value"><span>Employer evidence</span>${p.value}</div><div class="tags">${p.tech.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="project-actions"><button class="button case-btn" data-id="${p.id}" aria-label="View ${p.name} case study">View case study</button><button class="button ghost placeholder-link" type="button" disabled aria-label="${p.name} GitHub link placeholder">GitHub placeholder</button><button class="button ghost placeholder-link" type="button" disabled aria-label="${p.name} demo link placeholder">Demo placeholder</button><span class="status">${p.status}</span></div></article>`).join('');$('#result-count').textContent=`${list.length} project${list.length!==1?'s':''}`;$('#empty-state').hidden=!!list.length;$$('.case-btn').forEach(b=>b.onclick=()=>openModal(b.dataset.id));}
function openModal(id){const p=projects.find(x=>x.id===id);$('#modal-content').innerHTML=`<div class="modal-inner"><p class="kicker">CASE STUDY · ${p.status}</p><h2 id="modal-title">${p.name}</h2><p class="modal-lede">${p.overview}</p><div class="modal-grid"><section><h3>Problem</h3><p>${p.problem}</p></section><section><h3>Solution</h3><p>${p.solution}</p></section><section class="workflow"><h3>Architecture / workflow</h3><ol>${p.workflow.map(x=>`<li>${x}</li>`).join('')}</ol></section><section><h3>Key features</h3><ul>${p.features.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h3>Tech stack</h3><div class="tags">${p.tech.map(x=>`<span class="tag">${x}</span>`).join('')}</div></section><section><h3>Employer relevance</h3><p>${p.value}</p></section><section><h3>What this proves</h3><p>${p.proves}</p></section><section><h3>What I’d improve next</h3><p>${p.next}</p></section></div></div>`;modal.showModal();document.body.style.overflow='hidden'}

const projectLearning={
  agentguard:'Responsible AI is a systems problem: useful controls need clear thresholds, escalation paths and records—not just a safety prompt.',
  iris:'LLM assistance becomes more reliable when a long task is split into reviewable stages with structured outputs and explicit quality gates.',
  impact:'A technically possible AI idea is not automatically a good use case; value, ownership, data readiness and risk must be assessed together.',
  nestdore:'Recommendation quality depends as much on preference modelling and explanations as it does on the ranking calculation.',
  audit:'Fairness metrics need context. An audit should expose trade-offs and limitations instead of reducing model quality to one score.',
  casino:'A useful dashboard starts with consistent metric definitions and stakeholder questions, not with the largest possible set of charts.',
  jobmarket:'Noisy listing text needs a defensible taxonomy and careful cleaning before aggregate patterns can be treated as meaningful signals.',
  resume:'Similarity is evidence for review, not a hiring prediction. Users need to see the source text and uncertainty behind a score.',
  mixologist:'Even a lightweight recommender benefits from clear constraints, validation and explanations that help a user trust the result.'
};

function renderProjectVisual(p,large=false){
  const visualClass=`project-visual ${large?'project-visual-large':''} visual-${p.id}`;
  if(p.id==='casino'||p.id==='jobmarket'){
    const labels=p.id==='casino'?['Core customers','Growth segment','At-risk group']:['AI roles','Data skills','API demand'];
    return `<div class="${visualClass}" data-replaceable-visual="${p.id}"><div class="visual-ui-head"><span>${p.id==='casino'?'CUSTOMER INSIGHT':'MARKET SIGNALS'}</span><i></i></div><div class="mini-dashboard"><div class="mini-chart" aria-hidden="true">${[42,68,54,82,71,91,76].map((h,i)=>`<b style="--bar:${h}%"><em>${i+1}</em></b>`).join('')}</div><div class="mini-insights">${labels.map((x,i)=>`<span><strong>${String(i+1).padStart(2,'0')}</strong>${x}</span>`).join('')}</div></div></div>`;
  }
  if(p.id==='resume'){
    return `<div class="${visualClass}" data-replaceable-visual="${p.id}"><div class="visual-ui-head"><span>EXPLAINABLE MATCH REVIEW</span><i></i></div><div class="score-visual"><div class="score-ring"><strong>↔</strong><small>compare</small></div><div class="score-sources"><span>CV evidence</span><span>Role requirements</span></div><div class="gap-list"><b>Evidence matches</b><b>Keyword gaps</b><b>Review prompts</b></div></div></div>`;
  }
  if(p.id==='mixologist'){
    return `<div class="${visualClass}" data-replaceable-visual="${p.id}"><div class="visual-ui-head"><span>PREFERENCE RECOMMENDER</span><i></i></div><div class="recommend-visual"><span>Mood</span><span>Ingredients</span><i>→</i><strong>Rank</strong><i>→</i><b>Suggestions</b></div></div>`;
  }
  return `<div class="${visualClass}" data-replaceable-visual="${p.id}"><div class="visual-ui-head"><span>${p.name.toUpperCase()} · SYSTEM FLOW</span><i></i></div><div class="flow-visual">${p.workflow.map((step,i)=>`<div><small>0${i+1}</small><strong>${step}</strong></div>${i<p.workflow.length-1?'<span aria-hidden="true">→</span>':''}`).join('')}</div><div class="visual-feature-row">${p.features.slice(0,large?5:3).map(x=>`<span>${x}</span>`).join('')}</div></div>`;
}

const renderProjectsBase=renderProjects;
renderProjects=function(){
  renderProjectsBase();
  $$('.project-card').forEach(card=>{
    const p=projects.find(item=>item.id===card.dataset.id);
    const role=card.querySelector('.role-match');
    if(p&&role)role.insertAdjacentHTML('afterend',renderProjectVisual(p));
  });
};

const openModalBase=openModal;
openModal=function(id){
  openModalBase(id);
  const p=projects.find(item=>item.id===id);
  const gridEl=$('#modal-content .modal-grid');
  const workflowEl=$('#modal-content .workflow');
  if(p&&gridEl){
    workflowEl?.insertAdjacentHTML('beforebegin',`<section class="modal-visual-section"><h3>System preview</h3>${renderProjectVisual(p,true)}<p class="replace-hint">Designed as a lightweight architecture preview; replace with a verified product screenshot when available.</p></section>`);
    gridEl.insertAdjacentHTML('beforeend',`<section><h3>What I learned</h3><p>${projectLearning[p.id]}</p></section>`);
  }
};
function setRole(role,scroll=false){activeRole=role;$$('.role-tab').forEach(b=>b.setAttribute('aria-selected',b.dataset.role===role));const d=roleData[role];$('#role-output').innerHTML=`<div><p class="kicker">WHY I FIT · ${role}</p><h3>${d.pitch}</h3><h4>Recommended projects</h4><div class="role-projects">${d.projects.map(id=>{const p=projects.find(x=>x.id===id);return `<a href="#projects" data-project="${id}">${p.name} <span>↗</span></a>`}).join('')}</div></div><div><h4>Relevant technical skills</h4><div class="tags">${d.skills.map(x=>`<span class="tag">${x}</span>`).join('')}</div><h4>Suggested interview talking points</h4><ul class="role-list">${d.talk.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;$('#role-filter').value=role;renderProjects();if(scroll)$('#projects').scrollIntoView();}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)}

$('#tech-filter').innerHTML+=[...new Set(projects.flatMap(p=>p.tech))].sort().map(t=>`<option>${t}</option>`).join('');
$('#role-tabs').innerHTML=Object.keys(roleData).map((r,i)=>`<button class="button role-tab" role="tab" data-role="${r}" aria-selected="${i===0}">${r}</button>`).join('');
$('#skills-grid').innerHTML=Object.entries(skillGroups).map(([k,v])=>`<article class="skill-group"><h3>${k}</h3><div>${v.map(x=>`<span class="tag">${x}</span>`).join('')}</div></article>`).join('');
$('#impact-map').innerHTML=impacts.map((x,i)=>`<article class="impact-item"><span>0${i+1}</span><h3>${x[0]}</h3><p>Evidence: ${x[1]}</p></article>`).join('');
$('#project-search').addEventListener('input',renderProjects);$('#tech-filter').addEventListener('change',renderProjects);$('#role-filter').addEventListener('change',e=>{activeRole=e.target.value;renderProjects()});$$('.role-tab').forEach(b=>b.onclick=()=>setRole(b.dataset.role));
$('.modal-close').onclick=()=>modal.close();modal.addEventListener('close',()=>document.body.style.overflow='');modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.open)modal.close()});
$$('[data-copy],[data-copy-target]').forEach(b=>b.onclick=async()=>{const text=b.dataset.copy||$("#"+b.dataset.copyTarget).textContent.replace(/[“”]/g,'');try{await navigator.clipboard.writeText(text);showToast('Copied to clipboard')}catch{showToast('Copy unavailable — select the text manually')}});
$('#theme-toggle').onclick=()=>{const light=document.documentElement.classList.toggle('light');localStorage.setItem('theme',light?'light':'dark');$('#theme-toggle').setAttribute('aria-label',light?'Switch to dark mode':'Switch to light mode')};if(localStorage.getItem('theme')==='light')document.documentElement.classList.add('light');
$('#menu-toggle').onclick=()=>{const open=$('#nav-links').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',open)};$$('.nav-links a').forEach(a=>a.onclick=()=>$('#nav-links').classList.remove('open'));
$('#back-top').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#year').textContent=new Date().getFullYear();
$$('[data-open-project]').forEach(b=>b.onclick=()=>openModal(b.dataset.openProject));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
const sections=$$('main section[id]');const navObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('.nav-links a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}}),{rootMargin:'-30% 0px -60%'});sections.forEach(s=>navObserver.observe(s));
addEventListener('scroll',()=>{$('.site-header').classList.toggle('scrolled',scrollY>20);$('#back-top').classList.toggle('show',scrollY>600)},{passive:true});addEventListener('load',()=>document.body.classList.add('loaded'));
setRole('AI Engineer');
activeRole='all';
$('#role-filter').value='all';
renderProjects();
